services:
  - type: web
    name: pdf-splitter-api
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /api/health
